### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by mxsavchenko** [lomik/carbon-clickhouse#16]
Сегодня, ни с того ни с сего упал процесс с carbon-clickhouse, в логах при этом ничего нету, при повторном запуске выдает ошибку:
```
` carbon-clickhouse -config /etc/carbon-clickhouse/carbon-clickhouse.conf
panic: runtime error: index out of range

goroutine 10 [running]:
panic(0x84bba0, 0xc4200100f0)
        /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/lomik/carbon-clickhouse/uploader.(*Uploader).MakeTree(0xc420080dc0, 0xc420017ec0, 0x36, 0xc420011f00, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/lomik/carbon-clickhouse/_vendor/src/github.com/lomik/carbon-clickhouse/uploader/tree.go:99 +0xc59
github.com/lomik/carbon-clickhouse/uploader.(*Uploader).upload(0xc420080dc0, 0xc42005cba0, 0xc420017ec0, 0x36, 0x0, 0x0)
        /home/travis/gopath/src/github.com/lomik/carbon-clickhouse/_vendor/src/github.com/lomik/carbon-clickhouse/uploader/uploader.go:317 +0x44f
github.com/lomik/carbon-clickhouse/uploader.(*Uploader).uploadWorker(0xc420080dc0, 0xc42005cba0)
        /home/travis/gopath/src/github.com/lomik/carbon-clickhouse/_vendor/src/github.com/lomik/carbon-clickhouse/uploader/uploader.go:357 +0x13a
github.com/lomik/carbon-clickhouse/uploader.(*Uploader).(github.com/lomik/carbon-clickhouse/uploader.uploadWorker)-fm(0xc42005cba0)
        /home/travis/gopath/src/github.com/lomik/carbon-clickhouse/_vendor/src/github.com/lomik/carbon-clickhouse/uploader/uploader.go:148 +0x34
github.com/lomik/carbon-clickhouse/vendor/github.com/lomik/stop.(*Struct).StartFunc.func1.1(0xc42017ba90, 0xc42005cba0, 0xc420080dc0)
        /home/travis/gopath/src/github.com/lomik/carbon-clickhouse/_vendor/src/github.com/lomik/carbon-clickhouse/vendor/github.com/lomik/stop/stop.go:44 +0x30
created by github.com/lomik/carbon-clickhouse/vendor/github.com/lomik/stop.(*Struct).StartFunc.func1
        /home/travis/gopath/src/github.com/lomik/carbon-clickhouse/_vendor/src/github.com/lomik/carbon-clickhouse/vendor/github.com/lomik/stop/stop.go:46 +0x7d`

```

Версия carbon-clickhouse 0.6.3, Ubuntu 16.04 x64.
Обновился до 0.8.0 - ошибка та же.
Подскажите, пожалуйста, в чем может быть проблема?

**Comment by mxsavchenko** [comment]
В общем почистил каталог для буферизации данных и все заработало.

**Comment by lomik** [comment]
Я все-таки перепроверю проблемы в коде и потом закрою issue. После падения carbon-clickhouse должен уметь прочесть все файлы с диска. Даже битые и недописанные он должен читать сколько сможет. Падать не должен ни при каких условиях

**Comment by lomik** [comment]
А файлы на которых падало случайно не сохранились?

**Comment by lomik** [comment]
Воспроизвел. 
```
panic: runtime error: index out of range

goroutine 9 [running]:
panic(0x84bba0, 0xc4200120a0)
	/home/travis/.gimme/versions/go1.7.3.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/lomik/carbon-clickhouse/uploader.(*Uploader).MakeTree(0xc420082dc0, 0xc42065c1c0, 0x33, 0xc420013f00, 0x0, 0x0, 0x0)
	/.../carbon-clickhouse/uploader/tree.go:99 +0xc59
github.com/lomik/carbon-clickhouse/uploader.(*Uploader).upload(0xc420082dc0, 0xc42005cae0, 0xc42065c1c0, 0x33, 0x0, 0x0)
	/.../carbon-clickhouse/uploader/uploader.go:317 +0x44f
github.com/lomik/carbon-clickhouse/uploader.(*Uploader).uploadWorker(0xc420082dc0, 0xc42005cae0)
	/.../carbon-clickhouse/uploader/uploader.go:357 +0x13a
github.com/lomik/carbon-clickhouse/uploader.(*Uploader).(github.com/lomik/carbon-clickhouse/uploader.uploadWorker)-fm(0xc42005cae0)
	/.../carbon-clickhouse/uploader/uploader.go:148 +0x34
github.com/lomik/carbon-clickhouse/vendor/github.com/lomik/stop.(*Struct).StartFunc.func1.1(0xc420171a70, 0xc42005cae0, 0xc420082dc0)
	/.../carbon-clickhouse/vendor/github.com/lomik/stop/stop.go:44 +0x30
created by github.com/lomik/carbon-clickhouse/vendor/github.com/lomik/stop.(*Struct).StartFunc.func1
	/.../carbon-clickhouse/vendor/github.com/lomik/stop/stop.go:46 +0x7d
```
А в мастере под макосью так
```
panic: runtime error: index out of range

goroutine 7 [running]:
encoding/binary.binary.littleEndian.PutUint32(...)
	/usr/local/Cellar/go/1.9.3/libexec/src/encoding/binary/binary.go:68
github.com/lomik/carbon-clickhouse/helper/RowBinary.(*WriteBuffer).WriteUint32(...)
	/.../carbon-clickhouse/helper/RowBinary/write_buffer.go:117
github.com/lomik/carbon-clickhouse/uploader.(*Tree).parseFile(0xc42000e038, 0xc4201d67e0, 0x29, 0x18ffd80, 0xc42005e500, 0x0, 0x0, 0x0)
	/.../carbon-clickhouse/uploader/tree.go:85 +0xa03
github.com/lomik/carbon-clickhouse/uploader.(*Tree).(github.com/lomik/carbon-clickhouse/uploader.parseFile)-fm(0xc4201d67e0, 0x29, 0x18ffd80, 0xc42005e500, 0x1000, 0x1000, 0x0)
	/.../carbon-clickhouse/uploader/tree.go:22 +0x52
github.com/lomik/carbon-clickhouse/uploader.(*cached).upload(0xc42005e100, 0xc420020120, 0xc42009c360, 0xc4201d67e0, 0x29, 0x0, 0xc4200c13f0)
	/.../carbon-clickhouse/uploader/cached.go:66 +0x292
github.com/lomik/carbon-clickhouse/uploader.(*cached).(github.com/lomik/carbon-clickhouse/uploader.upload)-fm(0xc420020120, 0xc42009c360, 0xc4201d67e0, 0x29, 0x0, 0x0)
	/.../carbon-clickhouse/uploader/cached.go:21 +0x52
github.com/lomik/carbon-clickhouse/uploader.(*Base).uploadWorker(0xc4200abe00, 0xc420020120)
	/.../carbon-clickhouse/uploader/base.go:152 +0x328
github.com/lomik/carbon-clickhouse/uploader.(*Base).Start.func1.1(0xc420020120)
	/.../carbon-clickhouse/uploader/base.go:134 +0x34
github.com/lomik/carbon-clickhouse/vendor/github.com/lomik/stop.(*Struct).StartFunc.func1.1(0xc420044130, 0xc420020120, 0xc4200abe00)
	/.../carbon-clickhouse/vendor/github.com/lomik/stop/stop.go:44 +0x30
created by github.com/lomik/carbon-clickhouse/vendor/github.com/lomik/stop.(*Struct).StartFunc.func1
	/.../carbon-clickhouse/vendor/github.com/lomik/stop/stop.go:43 +0x7d
```
Можно получить, отправив метрику, которая при разворачивании в дерево не влезет в буфер

**Comment by lomik** [comment]
Исправил в мастере

**Comment by mxsavchenko** [comment]
Ок, спасибо!
